version: '3'
services:
  postgres:
    image: postgres:9.4
    volumes:
      - data_engine_api_vol:/data_engine_api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: circle_test
      POSTGRES_PASSWORD: ""
    ports:
     - "5432:5432"
  data_engine_api:
    build: .
    volumes:
      - data_engine_api_vol:/data_engine_api
    stdin_open: true
    tty: true
    links:
      - "postgres"
    depends_on:
      - postgres
    ports:
     - "5000:5000"

volumes:
  data_engine_api_vol:
