version: '3'
services:
  test:
    build: tests/integration/
    environment:
      API_HOST: 'data_engine_api:5000'
      PSQL_HOST: 'postgres'
    depends_on:
      - data_engine_api
      - postgres
    networks:
      - overlay
  postgres:
    image: postgres:9.4
    volumes:
      - data_engine_api_vol:/data_engine_api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: circle_test
      POSTGRES_PASSWORD: ""
    networks:
      - overlay
    ports:
     - "5432:5432"
  data_engine_api:
    image: gcr.io/${GOOGLE_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
    build: .
    volumes:
      - data_engine_api_vol:/data_engine_api
    stdin_open: true
    tty: true
    links:
      - "postgres"
    depends_on:
      - postgres
    networks:
      - overlay
    ports:
     - "5000:5000"

volumes:
  data_engine_api_vol:

networks:
  overlay:
